// Cross-cutting tags per block — generated (seed-block-tags workflow) from a
// controlled vocabulary so palette search + tag chips find a block by synonym
// and intent, not just its literal name. A block lives in ONE category but
// carries MANY tags. Lookup is by block id (= card type).

export const BLOCK_TAGS: Record<string, string[]> = {
  radial_gradient: ['gradient', 'field', 'smooth', 'color'],
  ring: ['primitive', 'polygon', 'round', 'geometric'],
  square: ['primitive', 'polygon', 'geometric'],
  rectangle: ['primitive', 'polygon', 'geometric'],
  rounded_box: ['primitive', 'polygon', 'curve', 'geometric'],
  triangle: ['primitive', 'polygon', 'geometric'],
  pentagon: ['primitive', 'polygon', 'geometric'],
  hexagon: ['primitive', 'polygon', 'geometric', 'pattern'],
  star: ['primitive', 'polygon', 'star', 'geometric'],
  heart: ['primitive', 'organic', 'heart'],
  cross: ['primitive', 'polygon', 'geometric'],
  arc: ['primitive', 'curve', 'polygon', 'round'],
  ellipse: ['primitive', 'round', 'curve', 'geometric'],
  capsule: ['primitive', 'curve', 'round', 'smooth'],
  segment: ['primitive', 'line', 'geometric'],
  trapezoid: ['primitive', 'polygon', 'geometric'],
  parallelogram: ['primitive', 'polygon', 'geometric'],
  vesica: ['primitive', 'curve', 'organic', 'geometric'],
  pie_slice: ['primitive', 'polygon', 'round'],
  horseshoe: ['primitive', 'curve', 'round'],
  stripes: ['pattern', 'line', 'stripe', 'repeat', 'geometric'],
  wavy_stripes: ['pattern', 'stripe', 'wave', 'distort', 'repeat'],
  radial_stripes: ['pattern', 'stripe', 'repeat', 'polar'],
  cross_hatch: ['pattern', 'line', 'geometric', 'grid'],
  hex_grid: ['tiling', 'grid', 'pattern', 'geometric'],
  triangle_grid: ['tiling', 'grid', 'pattern', 'geometric'],
  triangular_tiles: ['tiling', 'grid', 'pattern', 'geometric'],
  brick_wall: ['tiling', 'pattern', 'geometric', 'repeat'],
  random_squares: ['pattern', 'grid', 'cell', 'noise'],
  truchet: ['tiling', 'truchet', 'pattern', 'organic'],
  truchet_tris: ['tiling', 'truchet', 'pattern', 'geometric'],
  islamic_8pt_star: ['pattern', 'tiling', 'geometric', 'repeat'],
  islamic_6pt_star: ['pattern', 'tiling', 'geometric', 'repeat'],
  islamic_12pt_rosette: ['pattern', 'tiling', 'geometric', 'repeat'],
  zellige_grid: ['tiling', 'pattern', 'grid', 'geometric'],
  kufic_grid: ['tiling', 'pattern', 'grid', 'geometric'],
  arabesque_curls: ['pattern', 'organic', 'repeat', 'curve'],
  noise_field: ['noise', 'field', 'pattern', 'organic'],
  fbm: ['noise', 'field', 'fractal', 'organic'],
  ridged: ['noise', 'field', 'fractal', 'sharp'],
  turbulence: ['noise', 'field', 'organic', 'wave'],
  domain_warp: ['noise', 'distort', 'warp', 'organic'],
  voronoi_cells: ['noise', 'cell', 'voronoi', 'organic', 'pattern'],
  worley_edges: ['noise', 'voronoi', 'pattern', 'line'],
  sin_field: ['wave', 'pattern', 'field', 'geometric'],
  plasma: ['wave', 'field', 'pattern', 'vibrant', 'animated'],
  interference: ['wave', 'pattern', 'field', 'geometric'],
  moire: ['pattern', 'wave', 'line', 'grid'],
  caustics: ['pattern', 'caustics', 'organic', 'water'],
  julia: ['fractal', 'pattern', 'abstract', 'psychedelic'],
  mandelbrot: ['fractal', 'pattern', 'abstract', 'zoom'],
  mandelbulb_2d: ['fractal', 'pattern', 'abstract', 'zoom'],
  burning_ship: ['fractal', 'pattern', 'abstract', 'fire'],
  newton: ['fractal', 'pattern', 'abstract', 'geometric'],
  sierpinski: ['fractal', 'pattern', 'geometric', 'repeat'],
  orbit_trap_circle: ['fractal', 'pattern', 'abstract', 'smooth'],
  concentric: ['pattern', 'repeat', 'polar', 'geometric'],
  sunburst: ['pattern', 'polar', 'geometric', 'repeat'],
  rose_curve: ['pattern', 'polar', 'organic', 'geometric'],
  rose_petals: ['pattern', 'polar', 'organic', 'curve'],
  cardioid_shape: ['pattern', 'polar', 'organic', 'smooth'],
  lemniscate: ['pattern', 'polar', 'organic', 'smooth'],
  polar_grid: ['grid', 'pattern', 'polar', 'geometric'],
  metaballs: ['pattern', 'organic', 'smooth', 'abstract'],
  sector: ['primitive', 'polygon', 'round'],
  spiral_arms: ['pattern', 'swirl', 'polar', 'nature'],
  gradient_linear: ['gradient', 'color', 'smooth', 'geometric'],
  gradient_conic: ['gradient', 'color', 'smooth', 'polar'],
  translate: ['transform', 'warp', 'mix'],
  scale_uv: ['transform', 'zoom'],
  mirror_x: ['mirror', 'transform'],
  mirror_y: ['mirror', 'transform'],
  skew: ['transform', 'distort', 'geometric'],
  polar_warp: ['polar', 'transform', 'warp'],
  fisheye: ['fisheye', 'distort', 'warp'],
  zoom_blur_uv: ['zoom', 'blur', 'animated'],
  repeat: ['tiling', 'repeat', 'pattern'],
  polar_repeat: ['kaleidoscope', 'repeat', 'polar'],
  mirror_domain: ['kaleidoscope', 'mirror', 'repeat'],
  mirror_repeat: ['mirror', 'repeat', 'tiling'],
  swirl: ['swirl', 'twist', 'transform'],
  twirl: ['twist', 'warp', 'transform'],
  noise_warp: ['displace', 'warp', 'noise'],
  wave_warp: ['wave', 'warp', 'displace'],
  ripple: ['ripple', 'wave', 'displace'],
  threshold_d: ['posterize', 'sharp', 'edge'],
  invert_d: ['transform', 'color'],
  power_curve: ['transform', 'curve', 'smooth'],
  bands: ['posterize', 'stripe', 'pattern'],
  contour: ['outline', 'pattern', 'line'],
  sin_wave_d: ['ripple', 'wave', 'animated'],
  onion: ['outline', 'repeat', 'pattern'],
  antialiased_step: ['sharp', 'edge', 'smooth'],
  remap: ['transform', 'mix'],
  cubic_smoothstep: ['smooth', 'curve', 'transform'],
  sigmoid_curve: ['smooth', 'curve', 'transform'],
  smooth_min_d: ['smooth', 'mix'],
  smooth_min_to_circle: ['smooth', 'mix', 'geometric'],
  smooth_intersection: ['smooth', 'mix'],
  mouse_repel: ['mouse', 'feedback'],
  mouse_paint_d: ['mouse', 'feedback'],
  palette: ['color', 'gradient', 'ramp', 'mix'],
  triple_gradient: ['color', 'gradient', 'ramp', 'mix'],
  four_gradient: ['color', 'gradient', 'ramp', 'mix'],
  duotone: ['color', 'duotone', 'vibrant'],
  cosine_palette: ['color', 'gradient', 'ramp', 'smooth', 'palette'],
  rainbow_d: ['color', 'hue', 'vibrant', 'psychedelic'],
  hue_cycle: ['color', 'hue', 'animated', 'psychedelic'],
  d_as_rgb: ['color', 'grayscale', 'ramp'],
  solid_color: ['color', 'minimal', 'primitive'],
  tritone: ['color', 'ramp', 'lighting'],
  split_tone: ['color', 'duotone', 'lighting', 'tint'],
  palette_themed: ['color', 'palette', 'vibrant', 'abstract'],
  hue_shift: ['color', 'hue', 'transform'],
  saturate: ['color', 'vibrant', 'pastel', 'tint'],
  grayscale: ['color', 'grayscale'],
  sepia: ['color', 'grayscale', 'retro'],
  vignette: ['lighting', 'shadow', 'edge', 'vignette'],
  glow: ['lighting', 'glow', 'bloom'],
  bloom: ['lighting', 'glow', 'bloom', 'smooth'],
  god_rays: ['lighting', 'godrays', 'glow'],
  radial_blur_fake: ['zoom', 'blur', 'glow'],
  fog: ['fog', 'tint'],
  fog_exp: ['fog', 'tint'],
  sphere_ao: ['shadow', 'lighting', '3d'],
  rim_light: ['lighting', 'edge', 'glow', 'outline'],
  chromatic_aberration: ['color', 'distort', 'chromatic'],
  fresnel: ['lighting', 'edge', 'glow'],
  blinn_phong: ['lighting', 'sharpen', '3d'],
  ambient_occlusion: ['shadow', 'lighting', 'field'],
  soft_shadow: ['shadow', 'lighting', 'smooth'],
  contrast: ['color', 'sharpen'],
  exposure: ['color', 'sharpen'],
  gamma: ['color', 'tonemap'],
  dim: ['color', 'mix'],
  tint: ['color', 'tint', 'mix', 'hue'],
  reinhard_tonemap: ['tonemap', 'color'],
  aces_tonemap: ['tonemap', 'film', 'color'],
  filmic_tonemap: ['tonemap', 'film', 'color'],
  linear_to_srgb: ['tonemap', 'color'],
  halftone: ['retro', 'halftone', 'dither'],
  sketch: ['retro', 'sketch', 'outline'],
  ascii: ['retro', 'ascii'],
  dither: ['retro', 'dither', 'posterize', 'noise'],
  edge_detect: ['edge', 'outline', 'sharpen'],
  overlay_noise: ['grain', 'noise'],
  grain: ['grain', 'noise', 'film'],
  film_grain_color: ['grain', 'film', 'color', 'noise'],
  crt_curvature: ['retro', 'vhs', 'distort'],
  vhs_glitch: ['retro', 'glitch', 'vhs', 'scanline'],
  pulse_brightness: ['animated', 'wave'],
  pulse_hue: ['animated', 'hue', 'color'],
  mouse_glow: ['mouse', 'glow', 'feedback'],
  feedback_decay: ['feedback', 'animated'],
};

export const tagsFor = (id: string): string[] => BLOCK_TAGS[id] ?? [];

// Distinct tags ordered by how many blocks carry them (most useful chips
// first). Curated down to the cross-cutting ones that make good filters.
const _counts = new Map<string, number>();
for (const list of Object.values(BLOCK_TAGS)) {
  for (const t of list) _counts.set(t, (_counts.get(t) ?? 0) + 1);
}
export const TAG_LIST: string[] = [...(_counts.entries())]
  .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
  .map(([t]) => t);
